// Package thing provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package thing

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	JWTAuthScopes = "JWTAuth.Scopes"
)

// Defines values for ThingStatus.
const (
	Abandonné      ThingStatus = "Abandonné"
	Démoli         ThingStatus = "Démoli"
	EnConstruction ThingStatus = "En Construction"
	Planifié       ThingStatus = "Planifié"
	Utilisé        ThingStatus = "Utilisé"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Thing defines model for Thing.
type Thing struct {
	CreatedAt         *time.Time         `json:"_created_at,omitempty"`
	CreatedBy         *int32             `json:"_created_by,omitempty"`
	Deleted           *bool              `json:"_deleted,omitempty"`
	DeletedAt         *time.Time         `json:"_deleted_at,omitempty"`
	DeletedBy         *int32             `json:"_deleted_by,omitempty"`
	LastModifiedAt    *time.Time         `json:"_last_modified_at,omitempty"`
	LastModifiedBy    *int32             `json:"_last_modified_by,omitempty"`
	BuildAt           *string            `json:"build_at,omitempty"`
	Comment           *string            `json:"comment,omitempty"`
	ContainedBy       *string            `json:"contained_by,omitempty"`
	ContainedByOld    *int32             `json:"contained_by_old,omitempty"`
	Description       *string            `json:"description,omitempty"`
	ExternalId        *int32             `json:"external_id,omitempty"`
	ExternalRef       *string            `json:"external_ref,omitempty"`
	Id                openapi_types.UUID `json:"id"`
	Inactivated       bool               `json:"inactivated"`
	InactivatedBy     *int32             `json:"inactivated_by,omitempty"`
	InactivatedReason *string            `json:"inactivated_reason,omitempty"`
	InactivatedTime   *time.Time         `json:"inactivated_time,omitempty"`
	ManagedBy         *int32             `json:"managed_by,omitempty"`
	MoreDataSchema    *interface{}       `json:"more_data_schema,omitempty"`
	Name              string             `json:"name"`
	Position          *string            `json:"position,omitempty"`
	Status            *ThingStatus       `json:"status,omitempty"`
	TypeId            int32              `json:"type_id"`
	Validated         *bool              `json:"validated,omitempty"`
	ValidatedBy       *int32             `json:"validated_by,omitempty"`
	ValidatedTime     *time.Time         `json:"validated_time,omitempty"`
}

// ThingStatus defines model for Thing.Status.
type ThingStatus string

// ThingList defines model for ThingList.
type ThingList struct {
	CreatedAt   time.Time          `json:"created_at"`
	CreatedBy   int32              `json:"created_by"`
	Description *string            `json:"description,omitempty"`
	ExternalId  int32              `json:"external_id"`
	Id          openapi_types.UUID `json:"id"`
	Inactivated bool               `json:"inactivated"`
	Name        string             `json:"name"`
	TypeId      int32              `json:"type_id"`
}

// TypeThing defines model for TypeThing.
type TypeThing struct {
	CreatedAt         *time.Time   `json:"_created_at,omitempty"`
	CreatedBy         *int32       `json:"_created_by,omitempty"`
	Deleted           *bool        `json:"_deleted,omitempty"`
	DeletedAt         *time.Time   `json:"_deleted_at,omitempty"`
	DeletedBy         *int32       `json:"_deleted_by,omitempty"`
	LastModifiedAt    *time.Time   `json:"_last_modified_at,omitempty"`
	LastModifiedBy    *int32       `json:"_last_modified_by,omitempty"`
	Comment           *string      `json:"comment,omitempty"`
	Description       *string      `json:"description,omitempty"`
	ExternalId        *int32       `json:"external_id,omitempty"`
	GeometryType      *string      `json:"geometry_type,omitempty"`
	Id                int32        `json:"id"`
	Inactivated       *bool        `json:"inactivated,omitempty"`
	InactivatedBy     *int32       `json:"inactivated_by,omitempty"`
	InactivatedReason *string      `json:"inactivated_reason,omitempty"`
	InactivatedTime   *time.Time   `json:"inactivated_time,omitempty"`
	ManagedBy         *int32       `json:"managed_by,omitempty"`
	MoreDataSchema    *interface{} `json:"more_data_schema,omitempty"`
	Name              string       `json:"name"`
	TableName         *string      `json:"table_name,omitempty"`
}

// TypeThingList defines model for TypeThingList.
type TypeThingList struct {
	Id          int32  `json:"id"`
	Inactivated *bool  `json:"inactivated,omitempty"`
	Name        string `json:"name"`
}

// ListParams defines parameters for List.
type ListParams struct {
	// maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateJSONBody defines parameters for Create.
type CreateJSONBody = Thing

// ListByTypeParams defines parameters for ListByType.
type ListByTypeParams struct {
	// maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// TypeThingListParams defines parameters for TypeThingList.
type TypeThingListParams struct {
	// maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// TypeThingCreateJSONBody defines parameters for TypeThingCreate.
type TypeThingCreateJSONBody = TypeThing

// CreateJSONRequestBody defines body for Create for application/json ContentType.
type CreateJSONRequestBody = CreateJSONBody

// TypeThingCreateJSONRequestBody defines body for TypeThingCreate for application/json ContentType.
type TypeThingCreateJSONRequestBody = TypeThingCreateJSONBody
