// Package thing provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package thing

import (
	"time"
)

const (
	JWTAuthScopes = "JWTAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Thing defines model for Thing.
type Thing struct {
	Comment              *string    `json:"comment,omitempty"`
	CreateTime           time.Time  `json:"create_time"`
	Creator              int32      `json:"creator"`
	DeletedByUser        *int32     `json:"deleted_by_user,omitempty"`
	DeletedTime          *time.Time `json:"deleted_time,omitempty"`
	Description          *string    `json:"description,omitempty"`
	ExternalId           *int32     `json:"external_id,omitempty"`
	Id                   int32      `json:"id"`
	IdValidator          *int32     `json:"id_validator,omitempty"`
	InactivationReason   *string    `json:"inactivation_reason,omitempty"`
	InactivationTime     *time.Time `json:"inactivation_time,omitempty"`
	IsActive             bool       `json:"is_active"`
	IsDeleted            *bool      `json:"is_deleted,omitempty"`
	IsValidated          *bool      `json:"is_validated,omitempty"`
	LastModificationTime *time.Time `json:"last_modification_time,omitempty"`
	LastModificationUser *int32     `json:"last_modification_user,omitempty"`
	Name                 string     `json:"name"`
	TypeThingId          int32      `json:"type_thing_id"`
}

// ThingList defines model for ThingList.
type ThingList struct {
	CreateTime  time.Time `json:"create_time"`
	Creator     int32     `json:"creator"`
	Description *string   `json:"description,omitempty"`
	ExternalId  *int32    `json:"external_id,omitempty"`
	Id          int32     `json:"id"`
	IsActive    bool      `json:"is_active"`
	Name        string    `json:"name"`
	TypeThingId int32     `json:"type_thing_id"`
}

// TypeThing defines model for TypeThing.
type TypeThing struct {
	Comment              *string    `json:"comment,omitempty"`
	CreateTime           time.Time  `json:"create_time"`
	Creator              int32      `json:"creator"`
	Id                   int32      `json:"id"`
	InactivationReason   *string    `json:"inactivation_reason,omitempty"`
	InactivationTime     *time.Time `json:"inactivation_time,omitempty"`
	IsActive             bool       `json:"is_active"`
	LastModificationTime *time.Time `json:"last_modification_time,omitempty"`
	LastModificationUser *int32     `json:"last_modification_user,omitempty"`
	Name                 string     `json:"name"`
}

// TypeThingList defines model for TypeThingList.
type TypeThingList struct {
	Id       int32  `json:"id"`
	IsActive bool   `json:"is_active"`
	Name     string `json:"name"`
}

// ListParams defines parameters for List.
type ListParams struct {
	// maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateJSONBody defines parameters for Create.
type CreateJSONBody = Thing

// ListByTypeParams defines parameters for ListByType.
type ListByTypeParams struct {
	// maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// TypeThingListParams defines parameters for TypeThingList.
type TypeThingListParams struct {
	// maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// TypeThingCreateJSONBody defines parameters for TypeThingCreate.
type TypeThingCreateJSONBody = TypeThing

// CreateJSONRequestBody defines body for Create for application/json ContentType.
type CreateJSONRequestBody = CreateJSONBody

// TypeThingCreateJSONRequestBody defines body for TypeThingCreate for application/json ContentType.
type TypeThingCreateJSONRequestBody = TypeThingCreateJSONBody
