// Package objects provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package objects

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List returns a list of objects
	// (GET /objects)
	List(ctx echo.Context, params ListParams) error
	// Create will create a new object
	// (POST /objects)
	Create(ctx echo.Context) error
	// Delete allows to delete a specific objectId
	// (DELETE /objects/{objectId})
	Delete(ctx echo.Context, objectId int32) error
	// Get will retrieve in backend all information about a specific objectId
	// (GET /objects/{objectId})
	Get(ctx echo.Context, objectId int32) error
	// Update allows to modify information about a specific objectId
	// (PUT /objects/{objectId})
	Update(ctx echo.Context, objectId int32) error
	// ListByType returns a list of objects
	// (GET /objectsByType/{typeId})
	ListByType(ctx echo.Context, typeId int32, params ListByTypeParams) error
	// TypeObjectList returns a list of types
	// (GET /types)
	TypeObjectList(ctx echo.Context, params TypeObjectListParams) error
	// TypeObjectCreate will create a new group
	// (POST /types)
	TypeObjectCreate(ctx echo.Context) error
	// TypeObjectDelete allows to delete a specific typeObjectId
	// (DELETE /types/{typeObjectId})
	TypeObjectDelete(ctx echo.Context, typeObjectId int32) error
	// TypeObjectGet will retrieve in backend all information about a specific typeObjectId
	// (GET /types/{typeObjectId})
	TypeObjectGet(ctx echo.Context, typeObjectId int32) error
	// TypeObjectUpdate allows to modify information about a specific typeObjectId
	// (PUT /types/{typeObjectId})
	TypeObjectUpdate(ctx echo.Context, typeObjectId int32) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// List converts echo context to params.
func (w *ServerInterfaceWrapper) List(ctx echo.Context) error {
	var err error

	ctx.Set(JWTAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.List(ctx, params)
	return err
}

// Create converts echo context to params.
func (w *ServerInterfaceWrapper) Create(ctx echo.Context) error {
	var err error

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Create(ctx)
	return err
}

// Delete converts echo context to params.
func (w *ServerInterfaceWrapper) Delete(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "objectId" -------------
	var objectId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "objectId", runtime.ParamLocationPath, ctx.Param("objectId"), &objectId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter objectId: %s", err))
	}

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Delete(ctx, objectId)
	return err
}

// Get converts echo context to params.
func (w *ServerInterfaceWrapper) Get(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "objectId" -------------
	var objectId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "objectId", runtime.ParamLocationPath, ctx.Param("objectId"), &objectId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter objectId: %s", err))
	}

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Get(ctx, objectId)
	return err
}

// Update converts echo context to params.
func (w *ServerInterfaceWrapper) Update(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "objectId" -------------
	var objectId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "objectId", runtime.ParamLocationPath, ctx.Param("objectId"), &objectId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter objectId: %s", err))
	}

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Update(ctx, objectId)
	return err
}

// ListByType converts echo context to params.
func (w *ServerInterfaceWrapper) ListByType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "typeId" -------------
	var typeId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "typeId", runtime.ParamLocationPath, ctx.Param("typeId"), &typeId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter typeId: %s", err))
	}

	ctx.Set(JWTAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListByTypeParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ListByType(ctx, typeId, params)
	return err
}

// TypeObjectList converts echo context to params.
func (w *ServerInterfaceWrapper) TypeObjectList(ctx echo.Context) error {
	var err error

	ctx.Set(JWTAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params TypeObjectListParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.TypeObjectList(ctx, params)
	return err
}

// TypeObjectCreate converts echo context to params.
func (w *ServerInterfaceWrapper) TypeObjectCreate(ctx echo.Context) error {
	var err error

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.TypeObjectCreate(ctx)
	return err
}

// TypeObjectDelete converts echo context to params.
func (w *ServerInterfaceWrapper) TypeObjectDelete(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "typeObjectId" -------------
	var typeObjectId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "typeObjectId", runtime.ParamLocationPath, ctx.Param("typeObjectId"), &typeObjectId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter typeObjectId: %s", err))
	}

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.TypeObjectDelete(ctx, typeObjectId)
	return err
}

// TypeObjectGet converts echo context to params.
func (w *ServerInterfaceWrapper) TypeObjectGet(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "typeObjectId" -------------
	var typeObjectId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "typeObjectId", runtime.ParamLocationPath, ctx.Param("typeObjectId"), &typeObjectId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter typeObjectId: %s", err))
	}

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.TypeObjectGet(ctx, typeObjectId)
	return err
}

// TypeObjectUpdate converts echo context to params.
func (w *ServerInterfaceWrapper) TypeObjectUpdate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "typeObjectId" -------------
	var typeObjectId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "typeObjectId", runtime.ParamLocationPath, ctx.Param("typeObjectId"), &typeObjectId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter typeObjectId: %s", err))
	}

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.TypeObjectUpdate(ctx, typeObjectId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/objects", wrapper.List)
	router.POST(baseURL+"/objects", wrapper.Create)
	router.DELETE(baseURL+"/objects/:objectId", wrapper.Delete)
	router.GET(baseURL+"/objects/:objectId", wrapper.Get)
	router.PUT(baseURL+"/objects/:objectId", wrapper.Update)
	router.GET(baseURL+"/objectsByType/:typeId", wrapper.ListByType)
	router.GET(baseURL+"/types", wrapper.TypeObjectList)
	router.POST(baseURL+"/types", wrapper.TypeObjectCreate)
	router.DELETE(baseURL+"/types/:typeObjectId", wrapper.TypeObjectDelete)
	router.GET(baseURL+"/types/:typeObjectId", wrapper.TypeObjectGet)
	router.PUT(baseURL+"/types/:typeObjectId", wrapper.TypeObjectUpdate)

}
