/* tslint:disable */
/* eslint-disable */
/**
 * Thing microservice written in Golang
 * OpenApi Specification for an API to manage Thing
 *
 * The version of the OpenAPI document: 0.0.5
 * Contact: go-cloud-k8s-thing@goeland.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

