/* tslint:disable */
/* eslint-disable */
/**
 * Thing microservice written in Golang
 * OpenApi Specification for an API to manage Thing
 *
 * OpenAPI spec version: 0.0.5
 * Contact: go-cloud-k8s-thing@goeland.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum ThingStatus {
    Planifi = 'Planifié',
    EnConstruction = 'En Construction',
    Utilis = 'Utilisé',
    Abandonn = 'Abandonné',
    Dmoli = 'Démoli'
}

