/* tslint:disable */
/* eslint-disable */
/**
 * Thing microservice written in Golang
 * OpenApi Specification for an API to manage Thing
 *
 * OpenAPI spec version: 0.0.5
 * Contact: go-cloud-k8s-thing@goeland.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ThingStatus } from './thing-status';
/**
 * 
 * @export
 * @interface Thing
 */
export interface Thing {
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    typeId: number;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    comment?: string;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    externalId?: number;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    externalRef?: string;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    buildAt?: string;
    /**
     * 
     * @type {ThingStatus}
     * @memberof Thing
     */
    status?: ThingStatus;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    containedBy?: string;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    containedByOld?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Thing
     */
    inactivated: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Thing
     */
    inactivatedTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    inactivatedBy?: number;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    inactivatedReason?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Thing
     */
    validated?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Thing
     */
    validatedTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    validatedBy?: number;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    managedBy?: number;
    /**
     * 
     * @type {Date}
     * @memberof Thing
     */
    createAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    createBy: number;
    /**
     * 
     * @type {Date}
     * @memberof Thing
     */
    lastModifiedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    lastModifiedBy?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Thing
     */
    deleted: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Thing
     */
    deletedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    deletedBy?: number;
    /**
     * 
     * @type {any}
     * @memberof Thing
     */
    moreData?: any;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    posX: number;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    posY: number;
}
