/* tslint:disable */
/* eslint-disable */
/**
 * Thing microservice written in Golang
 * OpenApi Specification for an API to manage Thing
 *
 * OpenAPI spec version: 0.0.5
 * Contact: go-cloud-k8s-thing@goeland.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TypeThing
 */
export interface TypeThing {
    /**
     * 
     * @type {number}
     * @memberof TypeThing
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TypeThing
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TypeThing
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TypeThing
     */
    comment?: string;
    /**
     * 
     * @type {number}
     * @memberof TypeThing
     */
    externalId?: number;
    /**
     * 
     * @type {string}
     * @memberof TypeThing
     */
    tableName?: string;
    /**
     * 
     * @type {string}
     * @memberof TypeThing
     */
    geometryType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TypeThing
     */
    inactivated: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TypeThing
     */
    inactivatedTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof TypeThing
     */
    inactivatedBy?: number;
    /**
     * 
     * @type {string}
     * @memberof TypeThing
     */
    inactivatedReason?: string;
    /**
     * 
     * @type {number}
     * @memberof TypeThing
     */
    managedBy?: number;
    /**
     * 
     * @type {Date}
     * @memberof TypeThing
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof TypeThing
     */
    createdBy: number;
    /**
     * 
     * @type {Date}
     * @memberof TypeThing
     */
    lastModifiedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof TypeThing
     */
    lastModifiedBy?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TypeThing
     */
    deleted: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TypeThing
     */
    deletedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof TypeThing
     */
    deletedBy?: number;
    /**
     * 
     * @type {any}
     * @memberof TypeThing
     */
    moreDataSchema?: any;
}
