/* tslint:disable */
/* eslint-disable */
/**
 * Thing microservice written in Golang
 * OpenApi Specification for an API to manage Thing
 *
 * OpenAPI spec version: 0.0.5
 * Contact: go-cloud-k8s-thing@goeland.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ThingStatus } from './thing-status';
/**
 * 
 * @export
 * @interface Thing
 */
export interface Thing {
    /**
     * cet Universally unique identifier (UUID) sera généré automatiquement pour vous 
     * @type {string}
     * @memberof Thing
     */
    id: string;
    /**
     * FK sur la clé primaire du TypeThing de cet objet
     * @type {number}
     * @memberof Thing
     */
    typeId: number;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    comment?: string;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    externalId?: number;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    externalRef?: string;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    buildAt?: string;
    /**
     * 
     * @type {ThingStatus}
     * @memberof Thing
     */
    status?: ThingStatus;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    containedBy?: string;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    containedByOld?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Thing
     */
    inactivated: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Thing
     */
    inactivatedTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    inactivatedBy?: number;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    inactivatedReason?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Thing
     */
    validated?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Thing
     */
    validatedTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    validatedBy?: number;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    managedBy?: number;
    /**
     * date de création de cet enregistrement dans la base
     * @type {Date}
     * @memberof Thing
     */
    createdAt?: Date;
    /**
     * identifiant de l'utilisateur ayant créé cet enregistrement
     * @type {number}
     * @memberof Thing
     */
    createdBy: number;
    /**
     * date de la dernière modication de cet enregistrement
     * @type {Date}
     * @memberof Thing
     */
    lastModifiedAt?: Date;
    /**
     * utilisateur ayant effectué la dernière modication de cet enregistrement
     * @type {number}
     * @memberof Thing
     */
    lastModifiedBy?: number;
    /**
     * cet enregisrement a été marqué comme effacé
     * @type {boolean}
     * @memberof Thing
     */
    deleted: boolean;
    /**
     * date à laquelle cet enregisrement a été marqué comme effacé
     * @type {Date}
     * @memberof Thing
     */
    deletedAt?: Date;
    /**
     * utilisateur ayant demandé de marquer cet enregisrement comme effacé
     * @type {number}
     * @memberof Thing
     */
    deletedBy?: number;
    /**
     * permet de stocker des attributs complémentaires au format json
     * @type {any}
     * @memberof Thing
     */
    moreData?: any;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    posX: number;
    /**
     * 
     * @type {number}
     * @memberof Thing
     */
    posY: number;
}
