/**
 * Thing microservice written in Golang
 * OpenApi Specification for an API to manage Thing
 *
 * OpenAPI spec version: 0.0.5
 * Contact: go-cloud-k8s-thing@goeland.io
 *
 * NOTE: This class was auto generated by the  generator program.
 * npx openapi-generator-cli generate -i ../../../api/thing.yaml -g  typescript-axios -o ./openapi-generator-cli_thing_typescript-axios/
 * https://openapi-generator.tech/docs/generators/typescript-axios/
 * Do not edit the class manually.
 */
import { ThingStatus } from "./thing-status"
/**
 *
 * @export
 * @interface Thing
 */
//import { ThingStatus } from "../../../openapi-generator-cli_thing_typescript-axios";

export interface Thing {
  /**
   * cet Universally unique identifier (UUID) sera généré automatiquement pour vous
   * @type {string}
   * @memberof Thing
   */
  id: string
  /**
   * FK sur la clé primaire du TypeThing de cet objet
   * @type {number}
   * @memberof Thing
   */
  type_id: number
  /**
   *
   * @type {string}
   * @memberof Thing
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof Thing
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof Thing
   */
  comment?: string
  /**
   *
   * @type {number}
   * @memberof Thing
   */
  external_id?: number
  /**
   *
   * @type {string}
   * @memberof Thing
   */
  external_ref?: string
  /**
   *
   * @type {string}
   * @memberof Thing
   */
  build_at?: string
  /**
   *
   * @type {ThingStatus}
   * @memberof Thing
   */
  status?: ThingStatus
  /**
   *
   * @type {string}
   * @memberof Thing
   */
  contained_by?: string
  /**
   *
   * @type {number}
   * @memberof Thing
   */
  contained_by_old?: number
  /**
   *
   * @type {boolean}
   * @memberof Thing
   */
  inactivated: boolean
  /**
   *
   * @type {string}
   * @memberof Thing
   */
  inactivated_time?: string
  /**
   *
   * @type {number}
   * @memberof Thing
   */
  inactivated_by?: number
  /**
   *
   * @type {string}
   * @memberof Thing
   */
  inactivated_reason?: string
  /**
   *
   * @type {boolean}
   * @memberof Thing
   */
  validated?: boolean
  /**
   *
   * @type {string}
   * @memberof Thing
   */
  validated_time?: string
  /**
   *
   * @type {number}
   * @memberof Thing
   */
  validated_by?: number
  /**
   *
   * @type {number}
   * @memberof Thing
   */
  managed_by?: number
  /**
   * date de création de cet enregistrement dans la base
   * @type {string}
   * @memberof Thing
   */
  created_at?: string
  /**
   * identifiant de l\'utilisateur ayant créé cet enregistrement
   * @type {number}
   * @memberof Thing
   */
  created_by: number
  /**
   * date de la dernière modication de cet enregistrement
   * @type {string}
   * @memberof Thing
   */
  last_modified_at?: string
  /**
   * utilisateur ayant effectué la dernière modication de cet enregistrement
   * @type {number}
   * @memberof Thing
   */
  last_modified_by?: number
  /**
   * cet enregisrement a été marqué comme effacé
   * @type {boolean}
   * @memberof Thing
   */
  deleted: boolean
  /**
   * date à laquelle cet enregisrement a été marqué comme effacé
   * @type {string}
   * @memberof Thing
   */
  deleted_at?: string
  /**
   * utilisateur ayant demandé de marquer cet enregisrement comme effacé
   * @type {number}
   * @memberof Thing
   */
  deleted_by?: number
  /**
   * permet de stocker des attributs complémentaires au format json
   * @type {object}
   * @memberof Thing
   */
  more_data?: object
  /**
   *
   * @type {number}
   * @memberof Thing
   */
  pos_x: number
  /**
   *
   * @type {number}
   * @memberof Thing
   */
  pos_y: number
}
