/* tslint:disable */
/* eslint-disable */
/**
 * Thing microservice written in Golang
 * OpenApi Specification for an API to manage Thing
 *
 * OpenAPI spec version: 0.0.5
 * Contact: go-cloud-k8s-thing@goeland.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TypeThingList
 */
export interface TypeThingList {
    /**
     * 
     * @type {number}
     * @memberof TypeThingList
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TypeThingList
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof TypeThingList
     */
    externalId?: number;
    /**
     * 
     * @type {Date}
     * @memberof TypeThingList
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof TypeThingList
     */
    tableName?: string;
    /**
     * 
     * @type {string}
     * @memberof TypeThingList
     */
    geometryType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TypeThingList
     */
    inactivated: boolean;
}
